### PR TITLE
Protocol update

### PR DESCRIPTION
**Pull request by Piorin**
Created small update with section regarding protocols and examples.
Also included new entry in table of contents.

I will close the issue regarding protocols now - if there are still some issue with it please let me know here and I will fix them :)

P.S Please don't mind the merge from `protocol-update` branch to `Piorin/master` - I was just curious how merging works and I prefer to create separate branches for every single piece of functionality I'm working on - easier to rollback when something goes south ;)

### CODE REVIEW

**Comment by reinder42** [comment]
Great work! Thanks a lot :-)

I'm thinking, it would be cool if you added a paragraph/example about protocols as types. So say a property or variable needs a `Healer`, but doesn't care what type it is, as long as it conforms to `Healer`.

What do you think?

**Comment by Piorin** [comment]
Thanks! :)

I'm not sure if I understand correctly, but is it something like this(I found presentation from WWDC 2017 - session 402 "What's new in Swift" and SO topic):

Declaring a variable that Is a subclass of a type and implements one or more protocols:
```
var myVariable: MyClass & MyProtocol & MySecondProtocol
```
or as a parameter of a method:
```
func shakeEm(controls: [UIControl & Shakeable]) {}
```
it's one of those topics that I just have to repeat every few days no matter what I do, because I keep struggling with them :/ I will try to figure it out by myself and update you with further progress(or lack of it if I fail).

**Comment by reinder42** [comment]
No it's really just _Using protocols as Types_, see here: https://docs.swift.org/swift-book/LanguageGuide/Protocols.html#ID275

Think of it like a squad of Imperial soldiers that needs one soldier that conforms to `Healer`, but doesn't care what kind of soldier it is:

```swift
class Squad
{
	var leader:EliteStormtrooper
	var troopers:[StormTrooper]
	var healer:Healer
}

class StormtrooperPilot: Healer { }
class Jedi: Healer { }
class Stormtrooper { }
```

Above: you can assign `Jedi` or `StormtrooperPilot` to `healer`, because the `Healer` protocol is used as its type. Can't use `Stormtrooper` b/c doesn't conform to `Healer`. This protocols-as-types feature helps composability & flexibility.

**Comment by Piorin** [comment]
Oh ok - magic moment, everything "clicked" like it should :) Sometimes I tend to overcomplicate stuff when it's actually easy. Should I create separate PR for this or add as update to this? :)

**Comment by reinder42** [comment]
Awesome! Happens to me too :-) I think it's easiest if you add another commit to this PR. Found this on Google that explains some approaches: https://www.burntfen.com/2015-10-30/how-to-amend-a-commit-on-a-github-pull-request

**Comment by reinder42** [comment]
Hey @Piorin – you still want to update this? I appreciate your contributions :-) Cheers!

**Pull request closed without merging**
