### PR TITLE
Rename LICENSE

### PR DESCRIPTION
**Pull request by DaniSpringer**
Rename LICENSE to LICENSE.txt so the "open LICENSE(.txt)" command opens it in the default text editor, instead of "running it".

### CODE REVIEW

**Comment by reinder42** [comment]
Hmm. It's a common practice to name the license file just "LICENSE" – I see that everywhere. I think GitHub picks up on it too, and shows some of the attributes of the license within the repository.

Let's focus on the task at hand! I recently wrote a [blog post](https://learnappmaking.com/type-casting-swift-how-to/) about _type casting_ in Swift, but it hasn't been incorporated into the cheatsheet yet. Is that something you want to do? Just go over the article, and write 2-3 sentences about type casting, and examples for the `as`, `is`, `as!` and `as?` operators. It's great practice to learn-Swift-by-teaching!

**Comment by DaniSpringer** [comment]
Aha. Makes sense. 😊

Ok, I might try "pulling" that off. 😄

**Comment by DaniSpringer** [comment]
Do you by any chance use variables for the "issues" links in READMEs? Or do you actually hardcode the repo's name for every repo?

**Comment by reinder42** [comment]
Yes, the URLs are hardcoded for the reinder42/SwiftCheatsheet repo.

**Pull request closed without merging**
